// GENERATED by tools/gen_review.py. Do not edit by hand.
// Part 2 (practitioner) sections and fields, used by the page layout settings.
const ReviewSchema = {
 "sections": {
  "findings": "Screening Findings",
  "recommendations": "System Recommendations",
  "wound": "Wound Evaluation",
  "labs": "Lab Results",
  "pad": "Peripheral Arterial Disease",
  "infection": "Infection Management",
  "medications": "Medications",
  "adjunct": "Adjunctive Therapies",
  "orders": "Orders",
  "interpretation": "Clinical Interpretation",
  "referral": "Referral Decision",
  "plan": "Plan",
  "instructions": "Patient Instructions",
  "note": "Clinical Note",
  "signoff": "Sign-off"
 },
 "fields": [
  {
   "name": "r.w.1.onset",
   "label": "Onset / duration",
   "type": "radio",
   "options": [
    [
     "lt1w",
     "< 1 week"
    ],
    [
     "1-4w",
     "1–4 weeks"
    ],
    [
     "1-3m",
     "1–3 months"
    ],
    [
     "gt3m",
     "> 3 months"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.1.type",
   "label": "Type / cause",
   "type": "radio",
   "options": [
    [
     "neuropathic",
     "Neuropathic"
    ],
    [
     "ischaemic",
     "Ischaemic"
    ],
    [
     "neuroischaemic",
     "Neuro-ischaemic"
    ],
    [
     "pressure",
     "Pressure"
    ],
    [
     "trauma",
     "Trauma"
    ],
    [
     "surgical",
     "Surgical"
    ],
    [
     "other",
     "Other"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.1.length",
   "label": "Length",
   "type": "number",
   "unit": "cm",
   "min": 0.1,
   "max": 40,
   "step": "0.1",
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.1.width",
   "label": "Width",
   "type": "number",
   "unit": "cm",
   "min": 0.1,
   "max": 40,
   "step": "0.1",
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.1.depth",
   "label": "Depth",
   "type": "number",
   "unit": "cm",
   "min": 0,
   "max": 10,
   "step": "0.1",
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.1.tissue",
   "label": "Tissue bed",
   "type": "checkbox",
   "options": [
    [
     "granulation",
     "Granulation"
    ],
    [
     "slough",
     "Slough"
    ],
    [
     "necrosis",
     "Necrosis / eschar"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.1.signs",
   "label": "Local infection signs",
   "type": "checkbox",
   "options": [
    [
     "swelling",
     "Swelling / induration"
    ],
    [
     "erythema",
     "Erythema"
    ],
    [
     "tenderness",
     "Tenderness"
    ],
    [
     "warmth",
     "Warmth"
    ],
    [
     "purulent",
     "Purulent discharge"
    ],
    [
     "none",
     "None"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.1.erythema",
   "label": "Erythema extent from wound edge",
   "type": "number",
   "unit": "cm",
   "min": 0,
   "max": 50,
   "step": "0.5",
   "required": false,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.1.ptb",
   "label": "Probe-to-bone",
   "type": "radio",
   "options": [
    [
     "yes",
     "Positive"
    ],
    [
     "no",
     "Negative"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.1.exposed",
   "label": "Exposed structure",
   "type": "checkbox",
   "options": [
    [
     "tendon",
     "Tendon"
    ],
    [
     "joint",
     "Joint"
    ],
    [
     "bone",
     "Bone"
    ],
    [
     "none",
     "None"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.1.abscess",
   "label": "Abscess",
   "type": "radio",
   "options": [
    [
     "yes",
     "Yes"
    ],
    [
     "no",
     "No"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.1.gangrene",
   "label": "Gangrene",
   "type": "radio",
   "options": [
    [
     "none",
     "None"
    ],
    [
     "localized",
     "Localized (toe / forefoot)"
    ],
    [
     "extensive",
     "Extensive"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.1.osteomyelitis",
   "label": "Osteomyelitis",
   "type": "radio",
   "options": [
    [
     "no",
     "Not suspected"
    ],
    [
     "suspected",
     "Suspected"
    ],
    [
     "confirmed",
     "Confirmed"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.onset",
   "label": "Onset / duration",
   "type": "radio",
   "options": [
    [
     "lt1w",
     "< 1 week"
    ],
    [
     "1-4w",
     "1–4 weeks"
    ],
    [
     "1-3m",
     "1–3 months"
    ],
    [
     "gt3m",
     "> 3 months"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.type",
   "label": "Type / cause",
   "type": "radio",
   "options": [
    [
     "neuropathic",
     "Neuropathic"
    ],
    [
     "ischaemic",
     "Ischaemic"
    ],
    [
     "neuroischaemic",
     "Neuro-ischaemic"
    ],
    [
     "pressure",
     "Pressure"
    ],
    [
     "trauma",
     "Trauma"
    ],
    [
     "surgical",
     "Surgical"
    ],
    [
     "other",
     "Other"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.length",
   "label": "Length",
   "type": "number",
   "unit": "cm",
   "min": 0.1,
   "max": 40,
   "step": "0.1",
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.width",
   "label": "Width",
   "type": "number",
   "unit": "cm",
   "min": 0.1,
   "max": 40,
   "step": "0.1",
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.depth",
   "label": "Depth",
   "type": "number",
   "unit": "cm",
   "min": 0,
   "max": 10,
   "step": "0.1",
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.tissue",
   "label": "Tissue bed",
   "type": "checkbox",
   "options": [
    [
     "granulation",
     "Granulation"
    ],
    [
     "slough",
     "Slough"
    ],
    [
     "necrosis",
     "Necrosis / eschar"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.signs",
   "label": "Local infection signs",
   "type": "checkbox",
   "options": [
    [
     "swelling",
     "Swelling / induration"
    ],
    [
     "erythema",
     "Erythema"
    ],
    [
     "tenderness",
     "Tenderness"
    ],
    [
     "warmth",
     "Warmth"
    ],
    [
     "purulent",
     "Purulent discharge"
    ],
    [
     "none",
     "None"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.erythema",
   "label": "Erythema extent from wound edge",
   "type": "number",
   "unit": "cm",
   "min": 0,
   "max": 50,
   "step": "0.5",
   "required": false,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.ptb",
   "label": "Probe-to-bone",
   "type": "radio",
   "options": [
    [
     "yes",
     "Positive"
    ],
    [
     "no",
     "Negative"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.exposed",
   "label": "Exposed structure",
   "type": "checkbox",
   "options": [
    [
     "tendon",
     "Tendon"
    ],
    [
     "joint",
     "Joint"
    ],
    [
     "bone",
     "Bone"
    ],
    [
     "none",
     "None"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.abscess",
   "label": "Abscess",
   "type": "radio",
   "options": [
    [
     "yes",
     "Yes"
    ],
    [
     "no",
     "No"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.gangrene",
   "label": "Gangrene",
   "type": "radio",
   "options": [
    [
     "none",
     "None"
    ],
    [
     "localized",
     "Localized (toe / forefoot)"
    ],
    [
     "extensive",
     "Extensive"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.2.osteomyelitis",
   "label": "Osteomyelitis",
   "type": "radio",
   "options": [
    [
     "no",
     "Not suspected"
    ],
    [
     "suspected",
     "Suspected"
    ],
    [
     "confirmed",
     "Confirmed"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.onset",
   "label": "Onset / duration",
   "type": "radio",
   "options": [
    [
     "lt1w",
     "< 1 week"
    ],
    [
     "1-4w",
     "1–4 weeks"
    ],
    [
     "1-3m",
     "1–3 months"
    ],
    [
     "gt3m",
     "> 3 months"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.type",
   "label": "Type / cause",
   "type": "radio",
   "options": [
    [
     "neuropathic",
     "Neuropathic"
    ],
    [
     "ischaemic",
     "Ischaemic"
    ],
    [
     "neuroischaemic",
     "Neuro-ischaemic"
    ],
    [
     "pressure",
     "Pressure"
    ],
    [
     "trauma",
     "Trauma"
    ],
    [
     "surgical",
     "Surgical"
    ],
    [
     "other",
     "Other"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.length",
   "label": "Length",
   "type": "number",
   "unit": "cm",
   "min": 0.1,
   "max": 40,
   "step": "0.1",
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.width",
   "label": "Width",
   "type": "number",
   "unit": "cm",
   "min": 0.1,
   "max": 40,
   "step": "0.1",
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.depth",
   "label": "Depth",
   "type": "number",
   "unit": "cm",
   "min": 0,
   "max": 10,
   "step": "0.1",
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.tissue",
   "label": "Tissue bed",
   "type": "checkbox",
   "options": [
    [
     "granulation",
     "Granulation"
    ],
    [
     "slough",
     "Slough"
    ],
    [
     "necrosis",
     "Necrosis / eschar"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.signs",
   "label": "Local infection signs",
   "type": "checkbox",
   "options": [
    [
     "swelling",
     "Swelling / induration"
    ],
    [
     "erythema",
     "Erythema"
    ],
    [
     "tenderness",
     "Tenderness"
    ],
    [
     "warmth",
     "Warmth"
    ],
    [
     "purulent",
     "Purulent discharge"
    ],
    [
     "none",
     "None"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.erythema",
   "label": "Erythema extent from wound edge",
   "type": "number",
   "unit": "cm",
   "min": 0,
   "max": 50,
   "step": "0.5",
   "required": false,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.ptb",
   "label": "Probe-to-bone",
   "type": "radio",
   "options": [
    [
     "yes",
     "Positive"
    ],
    [
     "no",
     "Negative"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.exposed",
   "label": "Exposed structure",
   "type": "checkbox",
   "options": [
    [
     "tendon",
     "Tendon"
    ],
    [
     "joint",
     "Joint"
    ],
    [
     "bone",
     "Bone"
    ],
    [
     "none",
     "None"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.abscess",
   "label": "Abscess",
   "type": "radio",
   "options": [
    [
     "yes",
     "Yes"
    ],
    [
     "no",
     "No"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.gangrene",
   "label": "Gangrene",
   "type": "radio",
   "options": [
    [
     "none",
     "None"
    ],
    [
     "localized",
     "Localized (toe / forefoot)"
    ],
    [
     "extensive",
     "Extensive"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.w.3.osteomyelitis",
   "label": "Osteomyelitis",
   "type": "radio",
   "options": [
    [
     "no",
     "Not suspected"
    ],
    [
     "suspected",
     "Suspected"
    ],
    [
     "confirmed",
     "Confirmed"
    ]
   ],
   "required": true,
   "section": "wound",
   "sub": "Ulcers"
  },
  {
   "name": "r.lab.culture",
   "label": "Wound culture result",
   "type": "text",
   "required": false,
   "section": "labs",
   "sub": "Microbiology"
  },
  {
   "name": "r.lab.deepCulture",
   "label": "Bone / blood culture result",
   "type": "text",
   "required": false,
   "section": "labs",
   "sub": "Microbiology"
  },
  {
   "name": "r.pad.conclusion",
   "label": "PAD conclusion",
   "type": "radio",
   "options": [
    [
     "no-pad",
     "No PAD"
    ],
    [
     "pad",
     "PAD"
    ],
    [
     "clti",
     "Chronic limb-threatening ischaemia"
    ]
   ],
   "required": true,
   "section": "pad",
   "sub": "Assessment"
  },
  {
   "name": "r.pad.notes",
   "label": "Vascular notes",
   "type": "textarea",
   "required": false,
   "section": "pad",
   "sub": "Assessment"
  },
  {
   "name": "r.inf.antibiotics",
   "label": "Antibiotic plan",
   "type": "radio",
   "options": [
    [
     "none",
     "No antibiotics"
    ],
    [
     "oral",
     "Oral empiric"
    ],
    [
     "iv",
     "IV / parenteral"
    ]
   ],
   "required": true,
   "section": "infection",
   "sub": "Antibiotics"
  },
  {
   "name": "r.inf.agent",
   "label": "Agent and dose",
   "type": "text",
   "required": true,
   "section": "infection",
   "sub": "Antibiotics"
  },
  {
   "name": "r.inf.days",
   "label": "Planned duration",
   "type": "number",
   "unit": "days",
   "min": 1,
   "max": 90,
   "step": "1",
   "required": false,
   "section": "infection",
   "sub": "Antibiotics"
  },
  {
   "name": "r.inf.culture",
   "label": "Culture taken before antibiotics?",
   "type": "radio",
   "options": [
    [
     "yes",
     "Yes"
    ],
    [
     "no",
     "No"
    ],
    [
     "na",
     "Not applicable"
    ]
   ],
   "required": false,
   "section": "infection",
   "sub": "Monitoring"
  },
  {
   "name": "r.inf.reassess",
   "label": "Follow-up",
   "type": "checkbox",
   "options": [
    [
     "24-48h",
     "Reassess in 24–48 h"
    ]
   ],
   "required": false,
   "section": "infection",
   "sub": "Monitoring"
  },
  {
   "name": "r.inf.admit",
   "label": "Hospital admission needed?",
   "type": "radio",
   "options": [
    [
     "yes",
     "Yes"
    ],
    [
     "no",
     "No"
    ]
   ],
   "required": false,
   "section": "infection",
   "sub": "Monitoring"
  },
  {
   "name": "r.med.text",
   "label": "Medication, dose and instructions",
   "type": "textarea",
   "required": false,
   "section": "medications",
   "sub": "Medications"
  },
  {
   "name": "r.std.debridement",
   "label": "Debridement",
   "type": "radio",
   "options": [
    [
     "none",
     "None"
    ],
    [
     "sharp",
     "Sharp"
    ],
    [
     "enzymatic",
     "Enzymatic"
    ],
    [
     "autolytic",
     "Autolytic"
    ],
    [
     "mechanical",
     "Mechanical"
    ]
   ],
   "required": false,
   "section": "adjunct",
   "sub": "Standard wound care"
  },
  {
   "name": "r.std.offloading",
   "label": "Offloading",
   "type": "radio",
   "options": [
    [
     "none",
     "None"
    ],
    [
     "tcc",
     "Total contact cast"
    ],
    [
     "walker",
     "Removable walker"
    ],
    [
     "felt",
     "Felt padding"
    ],
    [
     "custom",
     "Custom shoes / insoles"
    ]
   ],
   "required": false,
   "section": "adjunct",
   "sub": "Standard wound care"
  },
  {
   "name": "r.std.dressing",
   "label": "Dressing",
   "type": "text",
   "required": false,
   "section": "adjunct",
   "sub": "Standard wound care"
  },
  {
   "name": "r.adj",
   "label": "Therapies",
   "type": "checkbox",
   "options": [
    [
     "npwt",
     "NPWT"
    ],
    [
     "hbot",
     "HBOT"
    ],
    [
     "topical-o2",
     "Topical oxygen"
    ],
    [
     "growth-factors",
     "Growth factors / placental products"
    ],
    [
     "prp",
     "PRP"
    ],
    [
     "none",
     "None"
    ]
   ],
   "required": false,
   "section": "adjunct",
   "sub": "Adjunctive therapies"
  },
  {
   "name": "r.orders.labsOther",
   "label": "Other tests (free text)",
   "type": "text",
   "required": false,
   "section": "orders",
   "sub": "Tests"
  },
  {
   "name": "r.orders.referrals",
   "label": "Referral orders",
   "type": "checkbox",
   "options": [
    [
     "podiatry",
     "Podiatry / wound care"
    ],
    [
     "vascular",
     "Vascular"
    ],
    [
     "id-surgical",
     "Infectious disease / surgical"
    ],
    [
     "orthotic",
     "Footwear / orthotic"
    ]
   ],
   "required": false,
   "section": "orders",
   "sub": "Referrals"
  },
  {
   "name": "r.int.skin",
   "label": "Deformity / skin diagnosis",
   "type": "text",
   "required": false,
   "section": "interpretation",
   "sub": "Impression"
  },
  {
   "name": "r.int.impression",
   "label": "Clinical impression",
   "type": "textarea",
   "required": true,
   "section": "interpretation",
   "sub": "Impression"
  },
  {
   "name": "r.ref.needed",
   "label": "Referral needed?",
   "type": "radio",
   "options": [
    [
     "yes",
     "Yes"
    ],
    [
     "no",
     "No"
    ]
   ],
   "required": true,
   "section": "referral",
   "sub": "Decision"
  },
  {
   "name": "r.ref.destination",
   "label": "Destination",
   "type": "radio",
   "options": [
    [
     "er",
     "Emergency department"
    ],
    [
     "tertiary",
     "Tertiary"
    ],
    [
     "secondary",
     "Secondary Care"
    ],
    [
     "vascular",
     "Vascular"
    ],
    [
     "wound-care",
     "Wound Care"
    ],
    [
     "private",
     "Private Center"
    ]
   ],
   "required": true,
   "section": "referral",
   "sub": "Decision"
  },
  {
   "name": "r.ref.urgency",
   "label": "Urgency",
   "type": "radio",
   "options": [
    [
     "routine",
     "Routine"
    ],
    [
     "soon",
     "Soon"
    ],
    [
     "urgent",
     "Urgent"
    ],
    [
     "emergency",
     "Emergency"
    ]
   ],
   "required": true,
   "section": "referral",
   "sub": "Decision"
  },
  {
   "name": "r.ref.timing",
   "label": "Timing",
   "type": "radio",
   "options": [
    [
     "today",
     "Today"
    ],
    [
     "24h",
     "≤ 24 h"
    ],
    [
     "week",
     "≤ 1 week"
    ],
    [
     "3weeks",
     "≤ 3 weeks"
    ],
    [
     "scheduled",
     "Scheduled"
    ]
   ],
   "required": true,
   "section": "referral",
   "sub": "Decision"
  },
  {
   "name": "r.ref.reason",
   "label": "Reason for referral",
   "type": "text",
   "required": false,
   "section": "referral",
   "sub": "Decision"
  },
  {
   "name": "r.plan.education",
   "label": "Advice given",
   "type": "checkbox",
   "options": [
    [
     "foot-care",
     "Foot-care education"
    ],
    [
     "self-check",
     "Daily self-check"
    ],
    [
     "footwear",
     "Footwear advice"
    ],
    [
     "glycaemic",
     "Glycaemic control reviewed"
    ]
   ],
   "required": true,
   "section": "plan",
   "sub": "Education"
  },
  {
   "name": "r.plan.offloading",
   "label": "Footwear / offloading plan",
   "type": "text",
   "required": false,
   "section": "plan",
   "sub": "Footwear & offloading"
  },
  {
   "name": "r.plan.followup",
   "label": "Follow-up interval",
   "type": "radio",
   "options": [
    [
     "48h",
     "48 hours"
    ],
    [
     "1w",
     "1 week"
    ],
    [
     "2w",
     "2 weeks"
    ],
    [
     "1m",
     "1 month"
    ],
    [
     "1-3m",
     "1–3 months"
    ],
    [
     "3-6m",
     "3–6 months"
    ],
    [
     "6-12m",
     "6–12 months"
    ],
    [
     "12m",
     "12 months"
    ]
   ],
   "required": true,
   "section": "plan",
   "sub": "Follow-up"
  },
  {
   "name": "r.plan.safetynet",
   "label": "Patient / carer",
   "type": "checkbox",
   "options": [
    [
     "understood",
     "Understands the plan and safety-net advice given"
    ]
   ],
   "required": true,
   "section": "plan",
   "sub": "Follow-up"
  }
 ]
};
